version: '3.8'

services:
  pycde:
    build: .
    container_name: pycde
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    logging:
      options:
        max-size: 1m
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - /projects:/project
    entrypoint: /run_jupyter.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
